CAtutorHTML8/ca_tutor/urls.py
from django.urls import path
from . import views

app_name = 'ca_tutor'

urlpatterns = [
    path('', views.index, name='index'),
    path('code/', views.code, name='code'),
    path('result/', views.result, name='result'),
]

CAtutorHTML8/ca_tutor/views.py
from django.shortcuts import render, redirect

def index(request):
    return render(request, 'catutor/index.html')

def code(request):
    return render(request, 'catutor/code.html')

def result(request):
    return render(request, 'catutor/result.html')

CAtutorHTML8/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}?ver{% now 'U' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.min.css' %}?ver{% now 'U' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'codemirror/codemirror.css' %}?ver{% now 'U' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://kit.fontawesome.com/f28dbb8460.js" crossorigin="anonymous"></script>
    <title>CA Tutor</title>
</head>
<body>
    {% if request.path == "/catutor/code/" %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a id="logo" class="navbar-brand" onclick="checkGoIndex()" href="#">CATutor</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-5 mb-2 mb-lg-0 navs">
                    <li class="nav-item mx-1"><a class="nav-link active text-white" onclick="checkGoIndex()" href="#">Home</a></li>
                    <li class="nav-item mx-1"><a class="nav-link active text-white" onclick="checkGoCode()" href="#">Code</a></li>
                    <li class="nav-item mx-1"><a class="nav-link active text-white" onclick="checkGoLogin()" href="#">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a id="logo" class="navbar-brand" href="{% url 'ca_tutor:index' %}">CATutor</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-5 mb-2 mb-lg-0 navs">
                    <li class="nav-item mx-1"><a class="nav-link active text-white" href="{% url 'ca_tutor:index' %}">Home</a></li>
                    <li class="nav-item mx-1"><a class="nav-link active text-white" href="{% url 'ca_tutor:code' %}">Code</a></li>
                    <li class="nav-item mx-1"><a class="nav-link active text-white" href="{% url 'ca_tutor:result' %}">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% endif %}
    <main>
    <!-- 상속받는 HTML파일의 Body가 들어가는 부분 -->
    {% block content %}
    {% endblock %}
    <!-- 상속받는 HTML파일의 Script가 들어가는 부분 -->
    </main>
    <!--bootstrap-->
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <!--codemirror-->
    <script src="{% static 'codemirror/codemirror.js' %}"></script>
    <script src="{% static 'codemirror/clike.js' %}"></script>
    {% block script %}
    <script type='text/javascript'>
        element.addEventListener('click', function() {
            if(confirm("삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
                // 확인 누르면 data-uri에 적용된 링크가 실행
            };
        });
    </script>
    {% endblock %}
    {% block css %}
    {% endblock %}
</body>
</html>

CAtutorHTML8/templates/catutor/code.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container my-3">
    <p id="title" class="text-center">Code Page</p>
    <button onclick="setColorMode()" id="color-mode-btn" class="btn btn-dark">Dark Mode</button>
    <label for="input-file" class="btn btn-secondary">
        <i class="fa fa-cloud-upload"></i> Upload .c
    </label>
    <input type="file" id="input-file" onchange="loadFile()" accept=".c" style="display: none;">
    <button onclick="clearEditor()" id="clear-btn" class="btn btn-outline-dark float-end">Clear</button> 
    <form action="{% url 'ca_tutor:result' %}" method="post" class="my-3">
        {% csrf_token %}
        <textarea id="codearea" class="codearea"></textarea>
        <div class="text-center mt-5">
            <input type="submit" id="coderesult" name="coderesult" value="Visualize Execution" class="btn btn-primary" style="width:200px;height:50px;font-size:18px;font-weight:600">
        </div>
    </form>
</div>
{% endblock %}
{% block script %}
<script src="{% static 'codestyle.js' %}"></script>
{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'codestyle.css' %}?ver{% now 'U' %}">
<link rel="stylesheet" type="text/css" href="{% static 'codemirror/3024-night.css' %}?ver{% now 'U' %}">
<link rel="stylesheet" type="text/css" href="{% static 'codemirror/neo.css' %}?ver{% now 'U' %}">
{% endblock %}

CAtutorHTML8/templates/catutor/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container my-4">
    <img class="rounde mx-auto d-block" width="30%" height="30%" src="{% static 'images/mips_jeans.png' %}"/>
</div>
<div class="container my-3">
    <p id="title" class="text-center">Visualize C code with CA tutor</p>
</div>
<div class="container my-3">
    <p class="text-center content">Detailed, fast, and simple Mips ISA Simulator. <br>
        Write your code, get deep understanding <br>
        of registers and memory change step-by-step.
    </p>
</div>
<br>
<div class="d-flex justify-content-center">
    <a href="https://github.com/judemario-kim/ca-tutor" target="_blank"><button type="button" class="btn btn-lg btn-secondary mx-5 index-btn"><i class="fa-brands fa-github icon-github"></i>&nbsp;&nbsp;Our Github</button></a>
    <a href="{% url 'ca_tutor:code' %}"><button type="button" class="btn btn-lg btn-dark mx-5 index-btn">Get Started</button></a>
</div>
{% endblock %}

CAtutorHTML8/templates/catutor/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" href="https://unpkg.com/xterm@3.6.0/dist/xterm.css" />

    <script src="https://unpkg.com/xterm@3.6.0/dist/xterm.js"></script>
    <script src="https://unpkg.com/xterm@3.6.0/dist/addons/fit/fit.js"></script>
    <script src="https://unpkg.com/xterm@3.6.0/dist/addons/fullscreen/fullscreen.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.4.0/socket.io.js"></script>
</head>

<div class="row mt-3 ms-4 me-4 gx-5">
    <div class="col" style="flex-direction:column;">
        <div class="d-flex align-items-center">
            <div class="sub-title">Code</div><button class="btn btn-secondary ms-auto">Convert</button>  
        </div>
        <div class="code-block border border-3 border-dark mt-2">
            <!-- 코드 불러오기 -->
            <div id="code" class="form-control border border-white bg-white mt-3" contenteditable="false">code area</div>
        </div>
        <div class="d-flex justify-content-center">
            <!-- 버튼 및 페이징 미구현 상태, 버튼 그리드 안망가지게 추후 변경할 것 -->
            <div class="mt-3 align-items-center">
                <button class="btn btn-outline-dark me-1">&lt;&lt; First</button>
                <button class="btn btn-outline-dark">&lt; Prev</button>
                <span class="px-1 mx-0">1/100</span> 
                <button class="btn btn-outline-dark">Next &gt;</button>
                <button class="btn btn-outline-dark ms-1">Last &gt;&gt;</button>
            </div>
        </div>
        <div class="mt-2">
            <div class="sub-title">Result</div>
        </div>
        <div class="result-block border border-3 border-dark mt-2">
            <!-- xterm 불러오기 -->
            <div style=" width: 100%; height:100%;" id="terminal"></div>
            <div id="result" class="form-control border border-white bg-white mt-3" contenteditable="false">xterm window</div>
        </div>
    </div>
    <div class="col">
        <div class="sub-title">Registers</div>
        <!-- 레지스터 표시 -->
        <div class="big-block border border-3 border-dark mt-2">
            <div class="row d-flex justify-content-center mt-3">
                {% include "register.html" with register_id=PC color="#683240" register_name="PC" margin="me-2" %}
                {% include "register.html" with register_id=IR color="#683240" register_name="IR" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=r0 color="#222222" register_name="r0" margin="me-2" %}
                {% include "register.html" with register_id=at color="#222222" register_name="at" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=v0 color="#222222" register_name="v0" margin="me-2" %}
                {% include "register.html" with register_id=v1 color="#222222" register_name="v1" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=a0 color="#251327" register_name="a0" margin="me-2" %}
                {% include "register.html" with register_id=a1 color="#251327" register_name="a1" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=a2 color="#251327" register_name="a2" margin="me-2" %}
                {% include "register.html" with register_id=a3 color="#251327" register_name="a3" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=t0 color="#001845" register_name="t0" margin="me-2" %}
                {% include "register.html" with register_id=t1 color="#001845" register_name="t1" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=t2 color="#001845" register_name="t2" margin="me-2" %}
                {% include "register.html" with register_id=t3 color="#001845" register_name="t3" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=t4 color="#001845" register_name="t4" margin="me-2" %}
                {% include "register.html" with register_id=t5 color="#001845" register_name="t5" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=t6 color="#001845" register_name="t6" margin="me-2" %}
                {% include "register.html" with register_id=t7 color="#001845" register_name="t7" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=s0 color="#1d3557" register_name="s0" margin="me-2" %}
                {% include "register.html" with register_id=s1 color="#1d3557" register_name="s1" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=s2 color="#1d3557" register_name="s2" margin="me-2" %}
                {% include "register.html" with register_id=s3 color="#1d3557" register_name="s3" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=s4 color="#1d3557" register_name="s4" margin="me-2" %}
                {% include "register.html" with register_id=s5 color="#1d3557" register_name="s5" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=s6 color="#1d3557" register_name="s6" margin="me-2" %}
                {% include "register.html" with register_id=s7 color="#1d3557" register_name="s7" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=t8 color="#444554" register_name="t8" margin="me-2" %}
                {% include "register.html" with register_id=t9 color="#444554" register_name="t9" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=k0 color="#444554" register_name="k0" margin="me-2" %}
                {% include "register.html" with register_id=k1 color="#444554" register_name="k1" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=gp color="#001219" register_name="gp" margin="me-2" %}
                {% include "register.html" with register_id=sp color="#001219" register_name="sp" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=fp color="#001219" register_name="fp" margin="me-2" %}
                {% include "register.html" with register_id=ra color="#001219" register_name="ra" margin="ms-2" %}
            </div>
            <div class="row d-flex justify-content-center mt-2">
                {% include "register.html" with register_id=HI color="#001219" register_name="HI" margin="me-2" %}
                {% include "register.html" with register_id=LO color="#001219" register_name="LO" margin="ms-2" %}
            </div>
        </div>
    </div>
    <div class="col">
        <div class="sub-title">Memory</div>
        <div class="big-block border border-3 border-dark mt-2">
            <!-- 메모리 표시 -->
            <div id="mem" class="form-control border border-white bg-white mt-3" contenteditable="false"></div>
        </div>
    </div>
</div>
<script>
        let xterm = new Xterm({
            rows: 22,
            cols: 10, //any value
        });

        //Terminal.applyAddon(fit)

        var socket = io.connect('https://xtermjs.run.goorm.site'); //{transports: ["websocket", "polling"]}');

        const status = document.getElementById("status")
        const button = document.getElementById("button")

        var term = new Terminal({
            cursorBlink: true,
        });

        
        term.open(document.getElementById('terminal'));

        Terminal.applyAddon(fit);
        term.fit()
        xterm.onResize(function (evt) {
            socket.send({ rows: evt.rows });
        });
        xterm.onResize(function (evt) {
        const terminal_size = {
            Width: evt.cols,
            Height: evt.rows,
        };
        socket.send("\x04" + JSON.stringify(terminal_size));
        });

        const xterm_resize_ob = new ResizeObserver(function (entries) {
        // since we are observing only a single element, so we access the first element in entries array
        try {
            fitAddon && fitAddon.fit();
        } catch (err) {
            console.log(err);
        }
        });

        // start observing for resize
        xterm_resize_ob.observe(document.querySelector("#xterm"));






        var sid = document.cookie.match('io=([^;]*)')[1];
        socket.on("pty_output", function(output){
            if (sid == output["sid"]){
                console.log(output["output"])
                term.write(output["output"])
            }
        })

        socket.on("connect", () => {
        status.innerHTML = '<span style="background-color: lightgreen;">connected</span>'
        button.innerHTML = 'Disconnect'
        })

        socket.on("disconnect", () => {
        status.innerHTML =  '<span style="background-color: #ff8383;">disconnected</span>'
        button.innerHTML = 'Connect'

        })
          
        function myFunction(){
            if (button.innerHTML =='Connect'){  
               location.reload();
            }

            else if (button.innerHTML == "Disconnect"){
                socket.emit("disconnect_request");
            }
        }
        
        function myFunction2(){
            socket.emit("do_something", "");
        }
          
        function myFunction3(){
            socket.emit("do_something2", "");
        }

        function resize(){
        term.fit()
        socket.emit("resize", {"cols": term.cols, "rows": term.rows})
        }

        window.onresize = resize
        window.onload = resize

      </script>
{% endblock %}
{% block script %}
<script src="{% static 'codestyle.js' %}"></script>
{% endblock %}

CAtutorHTML8/templates/register.html
<div class="col-md-5 px-1 {{margin}}">
    <div class="d-flex align-items-center bg-light rounded-3" style="border: 3px solid {{color}};">
        <div class="text-white text-center px-2 py-1" style="background-color: {{color}}; width:35px;">{{ register_name }}</div>
        <div id="{{register_id}}" class="flex-grow-1 text-right text-center"></div>
    </div>
</div>