CAtutorHTML1/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('temp/', include('temp.urls')),
]

CAtutorHTML1/temp/urls.py
from django.urls import path
from . import views

app_name = 'temp'

urlpatterns = [
    path('', views.index, name='index'),
    path('code/', views.code, name='code'),
]

CAtutorHTML1/temp/views.py
from django.shortcuts import render, redirect

def index(request):
    return render(request, 'temp/index.html')

def code(request):
    return render(request, 'temp/code.html')

CAtutorHTML1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://kit.fontawesome.com/f28dbb8460.js" crossorigin="anonymous"></script>
    <title>CA Tutor</title>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a id="logo" class="navbar-brand" href={% url 'temp:index' %}>CATutor</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-5 mb-2 mb-lg-0 navs">
                    <li class="nav-item mx-1"><a class="nav-link active text-white " aria-current="page" href="#">Home</a></li>
                    <li class="nav-item mx-1"><a class="nav-link active text-white" href="#">Code</a></li>
                    <li class="nav-item mx-1"><a class="nav-link active text-white" href="#">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
</head>
<body>
    <main class="container">
    <!-- 상속받는 HTML파일의 Body가 들어가는 부분 -->
    {% block content %}
    {% endblock %}
    <!-- 상속받는 HTML파일의 Script가 들어가는 부분 -->
    </main>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

CAtutorHTML1/templates/temp/code.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container my-3">
    <p id="title" class="text-center">Code Page</p>
</div>
{% endblock %}

CAtutorHTML1/templates/temp/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container my-4">
    <img class="rounde mx-auto d-block" width="30%" height="30%" src="{% static 'images/mips_jeans.png' %}"/>
</div>
<div class="container my-3">
    <p id="title" class="text-center">Visualize C code with CA tutor</p>
</div>
<div class="container my-3">
    <p class="text-center content">Detailed, fast, and simple Mips ISA Simulator. <br>
        Write your code, get deep understanding <br>
        of registers and memory change step-by-step.
    </p>
</div>
<br>
<div class="d-flex justify-content-center">
    <a href="https://github.com/judemario-kim/ca-tutor" target="_blank"><button type="button" style="width:200px;height:50px" class="btn btn-secondary btn-lg mx-5"><i class="fa-brands fa-github icon-github"></i>&nbsp;&nbsp;Our Github</button></a>
    <a href="{% url 'temp:code' %}"><button type="button" style="width:200px;height:50px" class="btn btn-dark btn-lg mx-5">Get Started</button></a>
</div>
{% endblock %}